name: image_cropper
description: A Flutter plugin for Android and iOS supports cropping images
version: 1.0.1
homepage: https://github.com/NaderRaida/UICropperClone

flutter:
  plugin:
    platforms:
      android:
        package: vn.hunghd.flutter.plugins.imagecropper
        pluginClass: ImageCropperPlugin
      ios:
        pluginClass: FLTImageCropperPlugin

environment:
  sdk: '>=1.20.1 <3.0.0'
  flutter: ^1.12.13

dependencies:
  flutter:
    sdk: flutter